/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 commercetools GmbH and the ct-builders contributors
 * Freely available, AS IS and UNSUPPORTED. See LICENSE.
 */

const mcApp = require('@commercetools-frontend/eslint-config-mc-app');

module.exports = [
  ...(Array.isArray(mcApp) ? mcApp : [mcApp]),
  {
    ignores: [
      'public/**',
      'node_modules/**',
      'dist/**',
      '.netlify/**',
      // Generated by `npm run build:harness` — a 2 MB esbuild bundle. Linting it
      // overflows ESLint's own formatter ("Invalid string length"), so the gate
      // fails on any machine that has run the harness build.
      'test/ui/harness.js',
      'test-results/**',
      'playwright-report/**',
    ],
  },
  {
    // The service and the Netlify function are plain Node ESM, not part of the
    // browser bundle. The mc-app config assumes a browser/React file.
    files: ['service/**/*.mjs', 'netlify/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Buffer: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'import/no-unresolved': 'off',
      // Node ESM REQUIRES the file extension on a relative import, so the
      // rule's advice is the opposite of what works here.
      'import/extensions': 'off',
    },
  },
];
